# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" ];
  boot.extraModprobeConfig = ''
    options v4l2loopback exclusive_caps=1
  '';
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
	boot.kernelParams = [ "nvidia.NVreg_PreserveVideoMemoryAllocations=1" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4ad2cd37-e6f2-4113-89ef-9e1df06f44b2";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/BA7E-001E";
      fsType = "vfat";
    };

  fileSystems."/mnt/LinuxMoment" =
    { device = "/dev/disk/by-uuid/1f40eba2-da8d-45a6-9c40-59926a4a8203";
      fsType = "ext4";
    };

  fileSystems."/mnt/Shindows" =
    { device = "/dev/disk/by-uuid/42BAA625BAA61607";
      fsType = "ntfs";
    };

  fileSystems."/mnt/disk_F" =
    { device = "/dev/disk/by-uuid/230B2C8C05A53430";
      fsType = "ntfs";
    };

  fileSystems."/mnt/Backups" =
    { device = "/dev/disk/by-uuid/68DC97236EBF416F";
      fsType = "ntfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
