[exit]
exit_command = [ "pkill", "-SIGUSR2", "waybar" ] # close waybar
locations = ["top"]
size = 24
margin = 0
timeout_ms = 10
color = "#FF000088"

[enter]
enter_command = [ "pkill", "-SIGUSR1", "waybar" ] # open waybar
locations = ["top"]
size = 1
margin = 0
timeout_ms = 10
color = "#FFFFFF88"
